---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Figure out what version of Apache is installed.
- name: Get installed version of Apache.
  shell: "{{ apache_daemon_path }}{{ apache_daemon }} -v"
  changed_when: false
  always_run: yes
  register: _apache_vhosts_version
  tags: skip_ansible_lint

- name: Create apache_vhosts_version variable.
  set_fact:
    apache_vhosts_version: "{{ _apache_vhosts_version.stdout.split()[2].split('/')[1] }}"

- include_vars: apache-22.yml
  when: "apache_vhosts_version.split('.')[1] == '2'"
  tags: skip_ansible_lint

- include_vars: apache-24.yml
  when: "apache_vhosts_version.split('.')[1] == '4'"
  tags: skip_ansible_lint

# Configure Apache vhosts.
- include: "configure-{{ ansible_os_family }}.yml"
  static: no
